<div class="footer-container">
    <footer class="content">
        <h3>
        	<a href="/">
        	<img src="/sites/all/themes/kimmyers/img/logo.png" alt="Kim Myers for Congress" class="logo" />
        	<span class="visuallyhidden">Kim Myers for Congress</span>
        	</a>
        </h3>
        <nav class="main">
	        <?php print render($page['footer_navigation']); ?>
        </nav>
        <nav class="social">
        	<ul>
        	    <li class="facebook"><a href="#" target="_blank"><img src="/sites/all/themes/kimmyers/img/facebook-icon.png" alt="Facebook" /></a></li>
        	    <li class="twitter"><a href="#" target="_blank"><img src="/sites/all/themes/kimmyers/img/twitter-icon.png" alt="Twitter" /></a></li>
        	</ul>
        </nav>
        <?php print render($page['footer']); ?>
    </footer>
</div>