<div class="header-container">
    <header class="clearfix">
        <h1>
        	<a href="/">
	        	<img src="/sites/all/themes/kimmyers/img/logo.png" alt="Kim Myers for Congress" class="logo" />
	        	<span class="visuallyhidden">Kim Myers for Congress</span>
	        </a>
        </h1>
        <nav class="social">
        	<ul>
        	    <li class="facebook"><a href="#" target="_blank"><img src="/sites/all/themes/kimmyers/img/facebook-icon.png" alt="Facebook" /></a></li>
        	    <li class="twitter"><a href="#" target="_blank"><img src="/sites/all/themes/kimmyers/img/twitter-icon.png" alt="Twitter" /></a></li>
        	</ul>
        </nav>
        <nav class="main">
        	<?php print render($page['navigation']); ?>
        </nav>
    </header>
</div>